### A Pluto.jl notebook ###
# v1.0.3

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    #! format: off
    return quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
    #! format: on
end

# ╔═╡ ffb28a87-801c-4ae0-8525-fe313e3128f9
begin
    using Pkg
    Pkg.activate(joinpath(@__DIR__, "..", "notebooks"))
end

# ╔═╡ 0d7491f7-6a63-4e6c-8c10-11b5a776d57b
begin
    using CYAxiverse
    using CairoMakie
    using ColorSchemes
    using HDF5
    using Statistics
    using Printf
    using PlutoUI
    const plotting = CYAxiverse.plotting
end

# ╔═╡ 3a8aef57-72ff-4679-93c9-9934a3545bfd
html"""
<style>
main {
    margin: 0 auto;
    max-width: 95%;
    padding-left: max(80px, 6%);
    padding-right: max(80px, 6%);
}
</style>
"""

# ╔═╡ fa21d463-1dcf-48ce-8dca-8904e8d7e7c7
md"""
# Orientifold axiverse database statistics

Publication-quality summary statistics for the orientifold axiverse
database generated by the Stage-1/Stage-2 geometry pipeline and the
vacua/inflation pipelines. This notebook only reads the persisted
`cyax.h5` files; it does not recompute geometries, spectra, or vacua.

Every figure uses the shared paper style
(`CYAxiverse.plotting.paper_style()`), rendered through the `CairoMakie`
extension. Set the database root below, or export
`CYAXIVERSE_ORIENTIFOLD_DB_ROOT` before starting Pluto, to point the
notebook at a different run without editing this file.
"""

# ╔═╡ 226c0c90-f819-4f78-9f72-541da589f35d
begin
    """Return the most recently named `orientifold_axiverse_database_*`
    directory beside the `CYAxiverse.jl` checkout, or `nothing` when none
    is found.

    The directory name carries a date suffix, so sorting the candidate
    names and keeping the last one selects the most recent run without
    hardcoding a path.
    """
    function discover_default_db_root()
        data_root = CYAxiverse.filestructure.default_data_dir()
        data_root === nothing && return nothing
        isdir(data_root) || return nothing
        candidates = filter(readdir(data_root)) do entry
            occursin(r"^orientifold_axiverse_database_", entry) &&
                isdir(joinpath(data_root, entry))
        end
        isempty(candidates) && return nothing
        return joinpath(data_root, sort(candidates)[end])
    end

    const DEFAULT_DB_ROOT = let
        configured = strip(get(ENV, "CYAXIVERSE_ORIENTIFOLD_DB_ROOT", ""))
        isempty(configured) ? something(discover_default_db_root(), "") : configured
    end
end

# ╔═╡ 900ed92d-3bfb-4950-aded-fccf7a3912c4
md"""
## Database selection

- Database root: $(@bind db_root PlutoUI.TextField(60; default=DEFAULT_DB_ROOT))

$(@bind reload_data PlutoUI.Button("Reload data"))
"""

# ╔═╡ 8dc935d4-968e-4810-9413-0f8bcf74f909
begin
    db_root_value = ismissing(db_root) ? DEFAULT_DB_ROOT : strip(db_root)
    reload_data_value = ismissing(reload_data) ? 0 : reload_data
end

# ╔═╡ e20855aa-2622-473e-b5b4-87d8967eef6e
begin
    """Return the sorted `h11` levels present as `h11_XXX` directories
    under `root`.
    """
    function discover_h11_levels(root::AbstractString)
        (isempty(root) || !isdir(root)) && return Int[]
        levels = Int[]
        for entry in readdir(root)
            level_match = match(r"^h11_(\d+)$", entry)
            level_match === nothing && continue
            isdir(joinpath(root, entry)) || continue
            push!(levels, parse(Int, level_match.captures[1]))
        end
        return sort(levels)
    end

    """Return the `(h11, tri, cy)` triples with a `cyax.h5` file present
    for one `h11` level under `root`.
    """
    function discover_geometries(root::AbstractString, h11::Int)
        level_dir = joinpath(root, "h11_" * lpad(h11, 3, "0"))
        isdir(level_dir) || return NTuple{3,Int}[]
        geometries = NTuple{3,Int}[]
        for polytope_entry in sort(readdir(level_dir))
            polytope_match = match(r"^np_(\d+)$", polytope_entry)
            polytope_match === nothing && continue
            polytope_dir = joinpath(level_dir, polytope_entry)
            isdir(polytope_dir) || continue
            tri = parse(Int, polytope_match.captures[1])
            for frst_entry in sort(readdir(polytope_dir))
                frst_match = match(r"^cy_(\d+)$", frst_entry)
                frst_match === nothing && continue
                frst_dir = joinpath(polytope_dir, frst_entry)
                isfile(joinpath(frst_dir, "cyax.h5")) || continue
                push!(geometries, (h11, tri, parse(Int, frst_match.captures[1])))
            end
        end
        return geometries
    end

    """Return the number of certified triangulation classes (`np_*`
    directories) at one `h11` level. Each class may contain more than one
    orientifold realization (`cy_*` directory).
    """
    function certified_class_count(root::AbstractString, h11::Int)
        level_dir = joinpath(root, "h11_" * lpad(h11, 3, "0"))
        isdir(level_dir) || return 0
        return count(readdir(level_dir)) do entry
            match(r"^np_\d+$", entry) !== nothing && isdir(joinpath(level_dir, entry))
        end
    end
end

# ╔═╡ 4e2befb6-f706-4471-b61e-aae976fb5f10
begin
    """Read one geometry's spectrum, vacuum, and inflation-diagnostic
    quantities from its `cyax.h5` file.

    Use the persisted `CYAxiverse.read` readers for the fields they cover:
    `physical_spectrum` for the `spectrum/physical` group, and
    `pipeline_vacua` for the `vacua_pipeline` group. No dedicated reader
    currently exposes the `lambda_31_log10`/`lambda_22_log10`
    cross-quartic couplings, or the `inflation` and `orientifold` groups,
    so those fields are read directly with HDF5.jl. Return `nothing` when
    the file is missing or cannot be read, so one damaged file does not
    stop the whole scan.
    """
    function read_geometry_row(root::AbstractString, h11::Int, tri::Int, cy::Int)
        ENV["CYAXIVERSE_DATA_DIR"] = root
        path = CYAxiverse.filestructure.cyax_file(h11, tri, cy)
        isfile(path) || return nothing
        try
            spectrum = CYAxiverse.read.physical_spectrum(h11, tri, cy)
            vacua = CYAxiverse.read.pipeline_vacua(h11, tri, cy)
            extra = HDF5.h5open(path, "r") do file
                physical = file["spectrum/physical"]
                catastrophes = file["inflation/catastrophes"]
                efolds = file["inflation/efolds"]
                orientifold = file["orientifold"]
                qcd_key = "cytools/geometric/visible_sector/qcd_divisor_volume"
                (;
                    lambda_31 = HDF5.read(physical, "lambda_31_log10"),
                    lambda_22 = HDF5.read(physical, "lambda_22_log10"),
                    saddle_count = Int(HDF5.read(catastrophes, "saddle_count")),
                    catastrophes_present = Int(HDF5.read(catastrophes, "catastrophes_present")) != 0,
                    leading_minima_count = Int(HDF5.read(catastrophes, "leading_minima_count")),
                    n_efold_candidates = Int(HDF5.read(efolds, "n_candidates")),
                    n_qualified_efolds = Int(HDF5.read(efolds, "n_qualified")),
                    h11_minus = Int(HDF5.read(orientifold, "h11_minus")),
                    qcd_divisor_volume = haskey(file, qcd_key) ?
                        Float64(HDF5.read(file, qcd_key)) : NaN,
                )
            end
            return (;
                h11 = h11, tri = tri, cy = cy,
                n_modes = length(spectrum.m),
                m = spectrum.m,
                fpert = spectrum.fpert,
                fK = spectrum.fK,
                lambda_self = spectrum.λself,
                lambda_31 = extra.lambda_31,
                lambda_22 = extra.lambda_22,
                n_vacua = vacua.estimate,
                vacua_issquare = vacua.issquare,
                vacua_verified = vacua.verified,
                saddle_count = extra.saddle_count,
                catastrophes_present = extra.catastrophes_present,
                leading_minima_count = extra.leading_minima_count,
                n_efold_candidates = extra.n_efold_candidates,
                n_qualified_efolds = extra.n_qualified_efolds,
                h11_minus = extra.h11_minus,
                qcd_divisor_volume = extra.qcd_divisor_volume,
            )
        catch error
            @warn "Could not read a geometry file; skipping it" h11 tri cy path error
            return nothing
        end
    end
end

# ╔═╡ 1d05d396-afe9-4c62-b8d0-42e9ef44ae7c
begin
    # Depend explicitly on the reload button so pressing it re-scans the
    # database root, picking up any geometries a certification job has
    # written since the last load.
    reload_data_value
    load_start_time = time()
    h11_levels = discover_h11_levels(db_root_value)
    certified_counts = Dict(h => certified_class_count(db_root_value, h) for h in h11_levels)
    geometry_index = Dict(h => discover_geometries(db_root_value, h) for h in h11_levels)
    geometry_counts = Dict(h => length(geometry_index[h]) for h in h11_levels)
    all_geometries = reduce(vcat, (geometry_index[h] for h in h11_levels); init = NTuple{3,Int}[])
    loaded_rows = [read_geometry_row(db_root_value, h, tri, cy) for (h, tri, cy) in all_geometries]
    rows = filter(!isnothing, loaded_rows)
    skipped_count = length(all_geometries) - length(rows)
    load_elapsed_seconds = time() - load_start_time
end

# ╔═╡ ba0cb6f4-128d-4f53-9c41-962d55d4b0ca
md"""
## Population and provenance

Loaded **$(length(rows))** geometry rows across **$(length(h11_levels))**
h11 levels from `$(db_root_value)` in **$(round(load_elapsed_seconds; digits=1))**
seconds; **$(skipped_count)** files were present on disk but could not be
read and were skipped.

Certified triangulation classes are `np_*` directories with an
``h^{1,1}_-=0``, ``h^{2,1}_+=0`` orientifold already written to disk; each
class may contain more than one orientifold realization (`cy_*`
directory, one `cyax.h5` row per realization). The Table 1 column below is
the published target from Sheridan, Carta, Gendler, McAllister, and Moritz
(arXiv:2412.12012), Table 1, also recorded in `docs/src/pipelines.md` and
`scripts/reproduce_fuzzy_axions_h11_4.py`.

Counts are read from the database root at run time, so a certification
job that is still appending geometries is reflected honestly rather than
baked in as a fixed number.
"""

# ╔═╡ a275d2a1-4cc9-4c56-ae26-6638d4138828
begin
    const TABLE1_TARGETS = Dict(2 => 11, 3 => 66, 4 => 267, 5 => 1033, 6 => 3623, 7 => 12253)

    population_lines = String[
        "| h11 | certified classes on disk | Table 1 target | fraction of target | axion spectra (cyax.h5 rows) |",
        "|--:|--:|--:|--:|--:|",
    ]
    for h in h11_levels
        certified = certified_counts[h]
        target = get(TABLE1_TARGETS, h, nothing)
        target_text = target === nothing ? "not tabulated" : string(target)
        fraction_text = target === nothing ? "n/a" : @sprintf("%.1f%%", 100 * certified / target)
        push!(population_lines,
            "| $(h) | $(certified) | $(target_text) | $(fraction_text) | $(geometry_counts[h]) |")
    end
    isempty(h11_levels) &&
        push!(population_lines, "| *(no h11 levels found under the selected root)* | | | | |")
    Markdown.parse(join(population_lines, "\n"))
end

# ╔═╡ 8934aa8e-c771-4521-bfaf-9270515d9069
md"""
## Distribution summary statistics

Median, mean, and standard deviation are computed over all axion modes
pooled across every certified geometry at each h11, except for the
vacuum count and saddle count, which are per-geometry scalars.
"""

# ╔═╡ 4c7b4484-389b-45e6-bde5-4505268a0594
begin
    """Return the values of a per-mode field, pooled across every row at
    one `h11`.
    """
    function pooled_mode_values(all_rows, h::Int, field::Symbol)
        values = Float64[]
        for row in all_rows
            row.h11 == h || continue
            append!(values, Float64.(getproperty(row, field)))
        end
        return values
    end

    """Return the per-geometry scalar values of a field at one `h11`."""
    function per_geometry_values(all_rows, h::Int, field::Symbol)
        return Float64[Float64(getproperty(row, field)) for row in all_rows if row.h11 == h]
    end

    """Return the value groups and levels restricted to non-empty entries.

    `CYAxiverse.plotting.boxplot` requires every input group to be
    non-empty. Use this helper to drop any h11 level with no data before
    calling it, so the notebook keeps working when a level has not
    produced any rows yet.
    """
    function nonempty_groups(levels::AbstractVector{<:Integer}, groups::AbstractVector)
        keep = map(!isempty, groups)
        return levels[keep], groups[keep]
    end

    """Format a short numeric summary, or a placeholder when `values` is
    empty.
    """
    function summary_cell_text(values::AbstractVector{<:Real})
        isempty(values) && return "no data"
        return @sprintf("%.3g / %.3g / %.3g", median(values), mean(values), std(values))
    end

    summary_lines = String[
        "| h11 | modes pooled | log10(m/eV) med/mean/std | log10(f_pert/GeV) med/mean/std | vacua per geometry med/mean/std | saddles per geometry med/mean/std |",
        "|--:|--:|:--|:--|:--|:--|",
    ]
    for h in h11_levels
        mass_summary_values = pooled_mode_values(rows, h, :m)
        fpert_summary_values = pooled_mode_values(rows, h, :fpert)
        vacua_summary_values = per_geometry_values(rows, h, :n_vacua)
        saddle_summary_values = per_geometry_values(rows, h, :saddle_count)
        push!(summary_lines,
            "| $(h) | $(length(mass_summary_values)) | $(summary_cell_text(mass_summary_values)) | " *
            "$(summary_cell_text(fpert_summary_values)) | $(summary_cell_text(vacua_summary_values)) | " *
            "$(summary_cell_text(saddle_summary_values)) |")
    end
    isempty(h11_levels) && push!(summary_lines, "| *(no data)* | | | | | |")
    Markdown.parse(join(summary_lines, "\n"))
end

# ╔═╡ 64f15683-7f9b-4c83-b1b5-a88195873a6c
begin
    style = plotting.paper_style()
    ENV["CYAXIVERSE_DATA_DIR"] = db_root_value
    plots_output_dir = isempty(db_root_value) ? mktempdir() : CYAxiverse.filestructure.plots_dir()
end

# ╔═╡ 5dc9f146-9e4d-4597-83c7-02015e76efae
md"""
## Axion mass spectrum

Distribution of ``\log_{10}(m_a/\mathrm{eV})`` for every retained
physical axion mode (masses above the persisted threshold,
`spectrum/physical/m`), pooled across all certified geometries at each
h11.
"""

# ╔═╡ 02574211-ffef-498f-b59f-273a2ad8441a
begin
    mass_groups_all = [pooled_mode_values(rows, h, :m) for h in h11_levels]
    if any(!isempty, mass_groups_all)
        mass_levels, mass_groups = nonempty_groups(h11_levels, mass_groups_all)
        mass_result = plotting.boxplot(mass_groups; style = style,
            positions = Float64.(mass_levels), labels = string.(mass_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\log_{10}(m_a/\mathrm{eV})$",
            title = "Axion mass spectrum by Hodge number")
        mass_figure_path = joinpath(plots_output_dir, "orientifold_mass_spectrum_by_h11.pdf")
        plotting.save_plot(mass_figure_path, mass_result)
        mass_result.figure
    else
        md"*No axion mass data is available for the selected database root.*"
    end
end

# ╔═╡ 2e7ded91-e56f-4c62-94c9-45a95549f1cb
md"""
Saved to `orientifold_mass_spectrum_by_h11.pdf` in the database's `plots`
directory. Boxes show the interquartile range with whiskers at
``1.5\times`` the interquartile range; crosses mark outliers beyond the
whiskers.
"""

# ╔═╡ 97166942-a2fa-43fd-a5a1-df49295c53c7
md"""
## Perturbative and Kähler decay constants

Two panels show ``\log_{10}(f_a/\mathrm{GeV})`` from the perturbative
estimate (`fpert_log10`) and from the Kähler-metric estimate
(`fK_log10`), pooled across every retained mode at each h11.
"""

# ╔═╡ d4277970-3ca5-43af-bb34-88b3f3bd918f
begin
    fpert_groups_all = [pooled_mode_values(rows, h, :fpert) for h in h11_levels]
    fK_groups_all = [pooled_mode_values(rows, h, :fK) for h in h11_levels]
    if any(!isempty, fpert_groups_all) || any(!isempty, fK_groups_all)
        decay_figure = Figure(size = style.resolution, fontsize = style.fontsize,
            figure_padding = style.figure_padding, backgroundcolor = style.background)
        fpert_levels, fpert_groups = nonempty_groups(h11_levels, fpert_groups_all)
        fK_levels, fK_groups = nonempty_groups(h11_levels, fK_groups_all)
        fpert_axis = plotting.styled_axis(decay_figure[1, 1]; style = style)
        fK_axis = plotting.styled_axis(decay_figure[1, 2]; style = style)
        !isempty(fpert_groups) && plotting.boxplot(fpert_groups; style = style, axis = fpert_axis,
            positions = Float64.(fpert_levels), labels = string.(fpert_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\log_{10}(f_{\mathrm{pert}}/\mathrm{GeV})$",
            title = "Perturbative decay constant")
        !isempty(fK_groups) && plotting.boxplot(fK_groups; style = style, axis = fK_axis,
            positions = Float64.(fK_levels), labels = string.(fK_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\log_{10}(f_{K}/\mathrm{GeV})$",
            title = "Kähler-metric decay constant")
        decay_figure_path = joinpath(plots_output_dir, "orientifold_decay_constants_by_h11.pdf")
        plotting.save_plot(decay_figure_path, decay_figure)
        decay_figure
    else
        md"*No decay-constant data is available for the selected database root.*"
    end
end

# ╔═╡ 8d1a2545-3c56-4a97-b89f-79a1c9a3934d
md"""
Saved to `orientifold_decay_constants_by_h11.pdf`. The two decay-constant
estimates probe different approximations of the same instanton geometry;
comparing panels shows how closely they agree as h11 grows.
"""

# ╔═╡ 3b9b79e0-5319-4570-a92f-6a8c732a014b
md"""
## Quartic self-interactions and cross-couplings

Three panels show ``\log_{10}|\lambda|`` for the diagonal self-coupling
(`lambda_self_log10`), the ``(i,i,i,j)`` cross-quartic
(`lambda_31_log10`), and the ``(i,i,j,j)`` cross-quartic
(`lambda_22_log10`), pooled across every retained instanton contraction
at each h11. Signs are stored separately (`*_sign`) and are not shown
here; these panels present magnitudes only.
"""

# ╔═╡ bc5eceb1-0bc7-4e27-b266-fb0209c348f6
begin
    self_groups_all = [pooled_mode_values(rows, h, :lambda_self) for h in h11_levels]
    l31_groups_all = [pooled_mode_values(rows, h, :lambda_31) for h in h11_levels]
    l22_groups_all = [pooled_mode_values(rows, h, :lambda_22) for h in h11_levels]
    if any(!isempty, self_groups_all) || any(!isempty, l31_groups_all) || any(!isempty, l22_groups_all)
        quartic_figure = Figure(size = (1350, style.resolution[2]), fontsize = style.fontsize,
            figure_padding = style.figure_padding, backgroundcolor = style.background)
        self_levels, self_groups = nonempty_groups(h11_levels, self_groups_all)
        l31_levels, l31_groups = nonempty_groups(h11_levels, l31_groups_all)
        l22_levels, l22_groups = nonempty_groups(h11_levels, l22_groups_all)
        self_axis = plotting.styled_axis(quartic_figure[1, 1]; style = style)
        l31_axis = plotting.styled_axis(quartic_figure[1, 2]; style = style)
        l22_axis = plotting.styled_axis(quartic_figure[1, 3]; style = style)
        !isempty(self_groups) && plotting.boxplot(self_groups; style = style, axis = self_axis,
            positions = Float64.(self_levels), labels = string.(self_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\log_{10}|\lambda_{\mathrm{self}}|$",
            title = "Diagonal self-coupling")
        !isempty(l31_groups) && plotting.boxplot(l31_groups; style = style, axis = l31_axis,
            positions = Float64.(l31_levels), labels = string.(l31_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\log_{10}|\lambda_{31}|$",
            title = "(i,i,i,j) cross-quartic")
        !isempty(l22_groups) && plotting.boxplot(l22_groups; style = style, axis = l22_axis,
            positions = Float64.(l22_levels), labels = string.(l22_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\log_{10}|\lambda_{22}|$",
            title = "(i,i,j,j) cross-quartic")
        quartic_figure_path = joinpath(plots_output_dir, "orientifold_quartic_couplings_by_h11.pdf")
        plotting.save_plot(quartic_figure_path, quartic_figure)
        quartic_figure
    else
        md"*No quartic-coupling data is available for the selected database root.*"
    end
end

# ╔═╡ af74bd59-c13d-4d7c-abe9-3be0ca32bc15
md"""
Saved to `orientifold_quartic_couplings_by_h11.pdf`. All three couplings
span many orders of magnitude even at fixed h11, reflecting the
exponential sensitivity of instanton actions to the Kähler moduli.
"""

# ╔═╡ 3502d56a-9f6f-449c-828a-234e8ee102a6
md"""
## Perturbative decay constant versus mass

Every point is one retained axion mode, colored by its geometry's h11.
"""

# ╔═╡ e8eec0fc-164c-4730-a929-20f36a301715
begin
    scatter_mass = Float64[]
    scatter_fpert = Float64[]
    scatter_h11 = Float64[]
    for row in rows
        append!(scatter_mass, row.m)
        append!(scatter_fpert, row.fpert)
        append!(scatter_h11, fill(Float64(row.h11), length(row.m)))
    end
    if !isempty(scatter_mass)
        mass_fpert_result = plotting.scatterplot(scatter_mass, scatter_fpert; style = style,
            color = scatter_h11, colorbar = true, colorbar_label = L"$h^{1,1}$",
            markersize = 6, xlabel = L"$\log_{10}(m_a/\mathrm{eV})$",
            ylabel = L"$\log_{10}(f_{\mathrm{pert}}/\mathrm{GeV})$",
            title = "Perturbative decay constant versus axion mass")
        mass_fpert_path = joinpath(plots_output_dir, "orientifold_fpert_vs_mass.pdf")
        plotting.save_plot(mass_fpert_path, mass_fpert_result)
        mass_fpert_result.figure
    else
        md"*No mass/decay-constant pairs are available for the selected database root.*"
    end
end

# ╔═╡ 0ec13b91-24cf-4abe-b140-cfedac12471a
md"""
Saved to `orientifold_fpert_vs_mass.pdf`.
"""

# ╔═╡ b4815701-219c-4647-9778-74d9b4e16c92
md"""
## Lightest retained mode versus mode count

Every point is one geometry: the number of retained physical axion modes
against the lightest retained mode's ``\log_{10}(m_a/\mathrm{eV})``,
colored by h11.
"""

# ╔═╡ 841731ae-6b86-413e-bab9-af70be34e160
begin
    lightest_mode_count = Float64[]
    lightest_mass = Float64[]
    lightest_h11 = Float64[]
    for row in rows
        isempty(row.m) && continue
        push!(lightest_mode_count, Float64(row.n_modes))
        push!(lightest_mass, minimum(row.m))
        push!(lightest_h11, Float64(row.h11))
    end
    if !isempty(lightest_mass)
        lightest_result = plotting.scatterplot(lightest_mode_count, lightest_mass; style = style,
            color = lightest_h11, colorbar = true, colorbar_label = L"$h^{1,1}$",
            markersize = 9, xlabel = "retained axion modes",
            ylabel = L"$\log_{10}(m_{a,\mathrm{min}}/\mathrm{eV})$",
            title = "Lightest retained mode versus mode count")
        lightest_path = joinpath(plots_output_dir, "orientifold_lightest_mass_vs_modes.pdf")
        plotting.save_plot(lightest_path, lightest_result)
        lightest_result.figure
    else
        md"*No per-geometry mode data is available for the selected database root.*"
    end
end

# ╔═╡ d37b1966-f24f-4556-8098-af7e35b78c42
md"""
Saved to `orientifold_lightest_mass_vs_modes.pdf`.
"""

# ╔═╡ c057b757-024e-4ddb-9963-7f3e787188fc
md"""
## Mass spectrum shape: empirical cumulative distribution

Empirical cumulative distribution functions make it easy to compare the
shape of the pooled mass distribution across h11 without choosing bins.
"""

# ╔═╡ 516693bc-988e-49c4-a46c-df9f27425100
begin
    """Return the empirical cumulative distribution function coordinates
    for `values`.
    """
    function ecdf_curve(values::AbstractVector{<:Real})
        sorted_values = sort(values)
        n = length(sorted_values)
        return sorted_values, collect((1:n) ./ n)
    end

    ecdf_curves = plotting.Curve[]
    for h in h11_levels
        ecdf_values = pooled_mode_values(rows, h, :m)
        isempty(ecdf_values) && continue
        ecdf_x, ecdf_y = ecdf_curve(ecdf_values)
        push!(ecdf_curves, plotting.curve(ecdf_x, ecdf_y; label = "h11 = $(h)"))
    end
    if !isempty(ecdf_curves)
        ecdf_result = plotting.functionplot(Tuple(ecdf_curves); style = style,
            xlabel = L"$\log_{10}(m_a/\mathrm{eV})$", ylabel = "empirical CDF",
            title = "Axion mass distribution shape by Hodge number", show_legend = true)
        ecdf_path = joinpath(plots_output_dir, "orientifold_mass_ecdf_by_h11.pdf")
        plotting.save_plot(ecdf_path, ecdf_result)
        ecdf_result.figure
    else
        md"*No axion mass data is available for the selected database root.*"
    end
end

# ╔═╡ a55df5a3-f2bd-459b-9dd4-6c6c6b7ea2c9
md"""
Saved to `orientifold_mass_ecdf_by_h11.pdf`. A curve shifted to the right
indicates a distribution weighted toward heavier retained modes at that
h11.
"""

# ╔═╡ bdff4ef4-0780-44ef-942b-ef268c1448f0
md"""
## Vacuum count per geometry

`vacua_pipeline/estimate` is the number of inequivalent vacua found by
the vacua pipeline for each geometry (`scripts/vacua_pipeline.jl`); the
box groups these per-geometry counts by h11.
"""

# ╔═╡ fdf5d0ab-ed43-4791-965d-43ba4dad6bd6
begin
    vacua_groups_all = [per_geometry_values(rows, h, :n_vacua) for h in h11_levels]
    if any(!isempty, vacua_groups_all)
        vacua_levels, vacua_groups = nonempty_groups(h11_levels, vacua_groups_all)
        vacua_result = plotting.boxplot(vacua_groups; style = style,
            positions = Float64.(vacua_levels), labels = string.(vacua_levels),
            xlabel = L"$h^{1,1}$", ylabel = L"$\mathcal{N}_{\mathrm{vac}}$",
            title = "Vacuum count per geometry")
        vacua_path = joinpath(plots_output_dir, "orientifold_vacua_count_by_h11.pdf")
        plotting.save_plot(vacua_path, vacua_result)
        vacua_result.figure
    else
        md"*No vacuum-count data is available for the selected database root.*"
    end
end

# ╔═╡ 44e044b2-64c0-424e-9704-6ff44fbcc39b
md"""
Saved to `orientifold_vacua_count_by_h11.pdf`. Verified and square-vacua
status per geometry are recorded in `vacua_pipeline/verified` and
`vacua_pipeline/issquare`; this panel presents the estimated count only.
"""

# ╔═╡ ea087f4f-3103-485b-8a34-340b087f8ac2
md"""
## Raw slow-roll search counts

`n_efold_candidates`, `n_qualified_efolds`, and `leading_minima_count`
are the raw outputs of the e-fold search
(`inflation/efolds/n_candidates`, `inflation/efolds/n_qualified`, and
`inflation/catastrophes/leading_minima_count`). At h11 = 2-5 almost every
geometry qualifies zero trajectories; the panels below show that
honestly rather than hiding the near-empty distributions.
"""

# ╔═╡ ba4ef886-d5e9-4610-b11a-01e7f1cf18c6
begin
    candidate_groups_all = [per_geometry_values(rows, h, :n_efold_candidates) for h in h11_levels]
    qualified_groups_all = [per_geometry_values(rows, h, :n_qualified_efolds) for h in h11_levels]
    leading_groups_all = [per_geometry_values(rows, h, :leading_minima_count) for h in h11_levels]
    if any(!isempty, candidate_groups_all) || any(!isempty, qualified_groups_all) ||
       any(!isempty, leading_groups_all)
        inflation_figure = Figure(size = (1350, style.resolution[2]), fontsize = style.fontsize,
            figure_padding = style.figure_padding, backgroundcolor = style.background)
        candidate_levels, candidate_groups = nonempty_groups(h11_levels, candidate_groups_all)
        qualified_levels, qualified_groups = nonempty_groups(h11_levels, qualified_groups_all)
        leading_levels, leading_groups = nonempty_groups(h11_levels, leading_groups_all)
        candidate_axis = plotting.styled_axis(inflation_figure[1, 1]; style = style)
        qualified_axis = plotting.styled_axis(inflation_figure[1, 2]; style = style)
        leading_axis = plotting.styled_axis(inflation_figure[1, 3]; style = style)
        !isempty(candidate_groups) && plotting.boxplot(candidate_groups; style = style,
            axis = candidate_axis, positions = Float64.(candidate_levels),
            labels = string.(candidate_levels), xlabel = L"$h^{1,1}$",
            ylabel = "e-fold candidates", title = "Raw candidates")
        !isempty(qualified_groups) && plotting.boxplot(qualified_groups; style = style,
            axis = qualified_axis, positions = Float64.(qualified_levels),
            labels = string.(qualified_levels), xlabel = L"$h^{1,1}$",
            ylabel = "qualified e-folds", title = "Qualified trajectories")
        !isempty(leading_groups) && plotting.boxplot(leading_groups; style = style,
            axis = leading_axis, positions = Float64.(leading_levels),
            labels = string.(leading_levels), xlabel = L"$h^{1,1}$",
            ylabel = "leading minima", title = "Leading minima count")
        inflation_path = joinpath(plots_output_dir, "orientifold_efold_counts_by_h11.pdf")
        plotting.save_plot(inflation_path, inflation_figure)
        inflation_figure
    else
        md"*No e-fold search data is available for the selected database root.*"
    end
end

# ╔═╡ 5187b806-4215-4bec-9350-ce320e427cc9
md"""
Saved to `orientifold_efold_counts_by_h11.pdf`. A box collapsed onto zero
means every geometry at that h11 produced zero qualified trajectories so
far; this is expected at low h11 and is reported as observed rather than
smoothed over.
"""

# ╔═╡ 51360cc3-8268-44c9-b4b2-8fa1c47a36dd
md"""
## Catastrophe search: saddle counts

`inflation/catastrophes/saddle_count` is the number of slow-roll saddle
points found by the catastrophe search for each geometry; every
certified geometry examined so far has at least one saddle
(`catastrophes_present = true`).
"""

# ╔═╡ 822cfed7-9876-4146-aaea-c42e7e7d017d
begin
    saddle_groups_all = [per_geometry_values(rows, h, :saddle_count) for h in h11_levels]
    catastrophe_present_count = count(row -> row.catastrophes_present, rows)
    catastrophe_present_fraction = isempty(rows) ? NaN :
        100 * catastrophe_present_count / length(rows)
    if any(!isempty, saddle_groups_all)
        saddle_levels, saddle_groups = nonempty_groups(h11_levels, saddle_groups_all)
        saddle_result = plotting.boxplot(saddle_groups; style = style,
            positions = Float64.(saddle_levels), labels = string.(saddle_levels),
            xlabel = L"$h^{1,1}$", ylabel = "saddle count",
            title = "Catastrophe search: saddle count per geometry")
        saddle_path = joinpath(plots_output_dir, "orientifold_saddle_count_by_h11.pdf")
        plotting.save_plot(saddle_path, saddle_result)
        saddle_result.figure
    else
        md"*No catastrophe-search data is available for the selected database root.*"
    end
end

# ╔═╡ c664175a-5f88-4e0c-bf1c-d7cdf7790296
md"""
Saved to `orientifold_saddle_count_by_h11.pdf`. Across all loaded
geometries, **$(catastrophe_present_count)** of **$(length(rows))**
($(isnan(catastrophe_present_fraction) ? "n/a" : @sprintf("%.1f%%", catastrophe_present_fraction)))
have at least one catastrophe saddle.
"""

# ╔═╡ c936e240-1866-4531-8162-2aed7e506fa5
md"""
## Notes on units and provenance

- Axion masses (`m`) are ``\log_{10}`` of the physical mass in eV; decay
  constants (`fpert`, `fK`) are ``\log_{10}`` of the decay constant in
  GeV. Both conventions follow `CYAxiverse.generate`'s physical-spectrum
  calculation (`src/generate.jl`), which adds the reduced Planck mass in
  GeV and, for masses only, a GeV-to-eV exponent offset.
- Quartic couplings (`lambda_self_log10`, `lambda_31_log10`,
  `lambda_22_log10`) are ``\log_{10}`` of the coupling magnitude; their
  signs are stored separately (`*_sign`) and are not shown in this
  notebook.
- All figures use `CYAxiverse.plotting.paper_style()` and are saved as
  vector PDFs beside the selected database root, under its `plots/`
  directory (`CYAxiverse.filestructure.plots_dir()`).
- This notebook reads only what is present under the selected database
  root at run time. A certification job may still be appending
  geometries under `h11_005`; re-running the "Reload data" button above
  picks up whatever has landed on disk without editing this file.
"""

# ╔═╡ Cell order:
# ╠═ffb28a87-801c-4ae0-8525-fe313e3128f9
# ╠═0d7491f7-6a63-4e6c-8c10-11b5a776d57b
# ╠═3a8aef57-72ff-4679-93c9-9934a3545bfd
# ╟─fa21d463-1dcf-48ce-8dca-8904e8d7e7c7
# ╠═226c0c90-f819-4f78-9f72-541da589f35d
# ╟─900ed92d-3bfb-4950-aded-fccf7a3912c4
# ╠═8dc935d4-968e-4810-9413-0f8bcf74f909
# ╠═e20855aa-2622-473e-b5b4-87d8967eef6e
# ╠═4e2befb6-f706-4471-b61e-aae976fb5f10
# ╠═1d05d396-afe9-4c62-b8d0-42e9ef44ae7c
# ╟─ba0cb6f4-128d-4f53-9c41-962d55d4b0ca
# ╠═a275d2a1-4cc9-4c56-ae26-6638d4138828
# ╟─8934aa8e-c771-4521-bfaf-9270515d9069
# ╠═4c7b4484-389b-45e6-bde5-4505268a0594
# ╠═64f15683-7f9b-4c83-b1b5-a88195873a6c
# ╟─5dc9f146-9e4d-4597-83c7-02015e76efae
# ╠═02574211-ffef-498f-b59f-273a2ad8441a
# ╟─2e7ded91-e56f-4c62-94c9-45a95549f1cb
# ╟─97166942-a2fa-43fd-a5a1-df49295c53c7
# ╠═d4277970-3ca5-43af-bb34-88b3f3bd918f
# ╟─8d1a2545-3c56-4a97-b89f-79a1c9a3934d
# ╟─3b9b79e0-5319-4570-a92f-6a8c732a014b
# ╠═bc5eceb1-0bc7-4e27-b266-fb0209c348f6
# ╟─af74bd59-c13d-4d7c-abe9-3be0ca32bc15
# ╟─3502d56a-9f6f-449c-828a-234e8ee102a6
# ╠═e8eec0fc-164c-4730-a929-20f36a301715
# ╟─0ec13b91-24cf-4abe-b140-cfedac12471a
# ╟─b4815701-219c-4647-9778-74d9b4e16c92
# ╠═841731ae-6b86-413e-bab9-af70be34e160
# ╟─d37b1966-f24f-4556-8098-af7e35b78c42
# ╟─c057b757-024e-4ddb-9963-7f3e787188fc
# ╠═516693bc-988e-49c4-a46c-df9f27425100
# ╟─a55df5a3-f2bd-459b-9dd4-6c6c6b7ea2c9
# ╟─bdff4ef4-0780-44ef-942b-ef268c1448f0
# ╠═fdf5d0ab-ed43-4791-965d-43ba4dad6bd6
# ╟─44e044b2-64c0-424e-9704-6ff44fbcc39b
# ╟─ea087f4f-3103-485b-8a34-340b087f8ac2
# ╠═ba4ef886-d5e9-4610-b11a-01e7f1cf18c6
# ╟─5187b806-4215-4bec-9350-ce320e427cc9
# ╟─51360cc3-8268-44c9-b4b2-8fa1c47a36dd
# ╠═822cfed7-9876-4146-aaea-c42e7e7d017d
# ╟─c664175a-5f88-4e0c-bf1c-d7cdf7790296
# ╟─c936e240-1866-4531-8162-2aed7e506fa5
