"""CYAX-0168 calibration and conformance helpers.

The package intentionally contains no database or backend integration.  The
generator is useful for the non-decision calibration/conformance boundary only.
"""

from .generator_primary import (
    GENERATOR_VERSION,
    NAMESPACE,
    PROFILES,
    TIERS,
    ASSERTION_PREIMAGE_KEYS,
    FIXED_TIME,
    Snapshot,
    GenerationError,
    GenerationFailure,
    frame,
    canonical_frame,
    canonical_json_bytes,
    entity_id,
    literal_id,
    source_revision_id,
    assertion_id,
    sha256_hex,
    prf_digest,
    generate_snapshot,
    logical_snapshot_checksum,
    semantic_projection_checksum,
    compute_logical_snapshot_checksum,
    physical_source_revisions,
    semantic_projection,
    compute_semantic_source_bundle_projection_checksum,
    dependency_target_rejects,
    fill_concerns_pair_rejects,
    prf_choice,
    prf_select,
)

__all__ = [
    "GENERATOR_VERSION",
    "NAMESPACE",
    "PROFILES",
    "TIERS",
    "ASSERTION_PREIMAGE_KEYS",
    "FIXED_TIME",
    "Snapshot",
    "GenerationError",
    "GenerationFailure",
    "frame",
    "canonical_frame",
    "canonical_json_bytes",
    "entity_id",
    "literal_id",
    "source_revision_id",
    "assertion_id",
    "sha256_hex",
    "prf_digest",
    "generate_snapshot",
    "logical_snapshot_checksum",
    "semantic_projection_checksum",
    "compute_logical_snapshot_checksum",
    "physical_source_revisions",
    "semantic_projection",
    "compute_semantic_source_bundle_projection_checksum",
    "dependency_target_rejects",
    "fill_concerns_pair_rejects",
    "prf_choice",
    "prf_select",
]
