"""Dependency-free version lifecycle primitives used by Gate A tooling."""

from .allocation import (
    AllocationResult,
    GlobalAllocationView,
    allocation_view,
    global_allocation_view,
    select_maintenance_dev,
    select_maintenance_version,
    select_principal_dev,
    select_principal_sentinel,
    validated_occupancy_proof,
)
from .codec import canonical_json, canonical_json_line, sha256_hex
from .static import (
    BlockedResult,
    CANONICAL_STATIC_ITERATION_SOURCE,
    canonical_static_iteration_source,
    SNAPSHOT_SCHEMA_VERSION,
    SnapshotStaleError,
    StaticSnapshot,
    StaticValidationError,
    build_static_snapshot,
    compute_static_snapshot,
    recompute_snapshot,
    recompute_snapshot_digests,
    snapshot_is_stale,
    static_iteration_snapshot,
    static_snapshot,
    validate_static_snapshot,
)
from .versions import (
    Version,
    as_version,
    final_version,
    maintenance_line,
    parse_package_version,
    parse_public_tag,
    parse_version,
    principal_sentinel,
    public_tag,
)


__all__ = [
    "AllocationResult",
    "allocation_view",
    "BlockedResult",
    "CANONICAL_STATIC_ITERATION_SOURCE",
    "canonical_static_iteration_source",
    "GlobalAllocationView",
    "SNAPSHOT_SCHEMA_VERSION",
    "SnapshotStaleError",
    "StaticSnapshot",
    "StaticValidationError",
    "Version",
    "as_version",
    "build_static_snapshot",
    "compute_static_snapshot",
    "canonical_json",
    "canonical_json_line",
    "final_version",
    "global_allocation_view",
    "maintenance_line",
    "parse_package_version",
    "parse_public_tag",
    "parse_version",
    "principal_sentinel",
    "public_tag",
    "recompute_snapshot_digests",
    "recompute_snapshot",
    "select_maintenance_dev",
    "select_maintenance_version",
    "select_principal_dev",
    "select_principal_sentinel",
    "validated_occupancy_proof",
    "sha256_hex",
    "static_iteration_snapshot",
    "snapshot_is_stale",
    "static_snapshot",
    "validate_static_snapshot",
]
