"""
    CYAxiverse
A Julia package for computing axion/ALP spectra and statistics using geometric data generated by [CYTools](https://cytools.liammcallistergroup.com/).

Load the optional CYTools integration after `using CYAxiverse`:
```julia
using PyCall
const CYTools = Base.get_extension(CYAxiverse, :CYAxiversePyCallExt)
CYTools.enable_cytools!()
```
"""
module CYAxiverse

include("structs.jl")
include("filestructure.jl")
include("read.jl")
include("minimizer.jl")
include("generate.jl")
include("../add_functions/profiling.jl")
include("plotting.jl")

if haskey(ENV, "SLURM_JOB_ID")
    include("slurm.jl")
end

export greet_CYAxiverse

greet_CYAxiverse() = "Hello CYAxiverse!"

end
